### ISSUE TITLE
the question of  HrrsUrlEncodedFormHelper.java code 

### ISSUE THREAD

**Issue by JerryXia** [vy/hrrs#6] opened 2018-04-10 01:36 UTC
https://github.com/vy/hrrs/blob/d67a42ec9c6fad72f3e60916393dde989f6fd278/servlet-filter/src/main/java/com/vlkan/hrrs/servlet/HrrsUrlEncodedFormHelper.java#L94

If current request infomation is: 
   post  http://www.abc.com/queryWithTheSameParamA?a=a1&b=b1
   Form Data: a=a1&c=c1

Is the current formParameter.get("a") has'nt the item "a1"?

**Comment by JerryXia** [comment] 2018-04-12 13:05
I'm trying to resolve this problem in my project, see the link below.

https://github.com/JerryXia/BizHttpRequestTest/blob/3099d3dce4210563991b1845d68173f4bac1ec97/source/devhelper/src/main/java/com/github/jerryxia/devhelper/requestcapture/support/servlet/RequestCaptureFilter.java#L398

Do you think my code works?

**Comment by vy** [comment] 2018-04-15 14:27
@JerryXia, I am closing the issue since it has nothing to do with HRRS.

Coming back to your question, I don't know what you're trying to do, but the problem is as simple as this: Using `ServletRequest#getParameterMap()`, there is no way to determine if a parameter appears both in query and form parameters, to the best of my knowledge.

**Closed by vy** 2018-04-15 14:27 UTC
